title: Your Site Title
description: Your site description
url: "https://guilhermevigneron.github.io"
theme: jekyll-theme-minimal

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - tests/ 
