name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install

      - name: Security Audit
        run: npm run test:security

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Jekyll
        run: gem install jekyll bundler
      
      - name: Build Jekyll site for validation
        run: jekyll build
      
      - name: HTML Validation
        run: npm run test:html

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: "./_site/**/*.html"

      - name: Run All Browser-Based Tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          build: jekyll build
          start: jekyll serve
          wait-on: 'http://localhost:4000'
          browser: chrome