name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Security Audit
        run: npm run test:security

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Jekyll
        run: gem install jekyll bundler
      
      - name: Build Jekyll site
        run: jekyll build
      
      - name: HTML Validation
        run: npm run test:html

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: "./_site/**/*.html"

      - name: Install correct ChromeDriver
        run: npx browser-driver-manager install chrome
        
      - name: Serve Jekyll site
        run: |
          nohup jekyll serve &
          sleep 15

      - name: Accessibility test
        run: npm run test:accessibility

      - name: Performance test
        run: npm run test:performance

      - name: E2E tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
