name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Jekyll
        run: gem install jekyll bundler
      
      - name: Build and serve Jekyll site
        run: |
          jekyll build
          nohup jekyll serve &
          sleep 15

      - name: Accessibility test
        run: npm run test:accessibility

      - name: Performance test
        run: npm run test:performance
